-- MySQL Script generated by MySQL Workbench
-- Tue Apr 26 00:46:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema programacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema programacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `programacion` DEFAULT CHARACTER SET utf8 ;
USE `programacion` ;

-- -----------------------------------------------------
-- Table `programacion`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programacion`.`usuario` (
  `Codigo` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Rol` VARCHAR(45) NULL,
  `Clave` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
